### ISSUE TITLE
Infografía Actividad 7 - Arcángel GC

### ISSUE THREAD

**Issue by ArcangelGC** [SistemasTecTlaxiaco/infografia-de-hilos-ArcangelGC#2]
[Infografía Trabajo 7 - Arcángel González.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-ArcangelGC/files/15043970/Infografia.Trabajo.7.-.Arcangel.Gonzalez.pdf)

**Comment by RodolfoNV** [comment]
Calificación 18

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
